### ISSUE TITLE
please reimplement graphics.setColor(byte, byte, byte, byte) as overload

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#19]
please reimplement graphics.setColor(byte, byte, byte, byte) as overload,

the only reason why I would see the lua version not doing this is because lua doesn't have function overloads.

**Comment by endlesstravel** [comment]
Did you mean color values is [0-255] from LÖVE 11.0 it changed all color values to be in the range 0-1, rather than 0-255.

why no use Graphics.SetColor( r / 255f, g / 255f, b / 255f, a / 255f ) to replace ?

reimplement Graphics.SetColor(byte, byte, byte, byte)  will confuse with Graphics.SetColor(float, float, float, float)

**Comment by Shadowblitz16** [comment]
dividing by 255f would work but I just thought it would be a nice feature to be able to pass in 0-255  ranges as well. since C# supports overloads.

as for being confusing there could just be intellisense documentation that says the values range from 0-1 or 0-255 when you start typing the function.

**Comment by endlesstravel** [comment]
wow. Let me delay.

may be Graphics.SetColor(Color c) with Color.RGBA32(float,float,float,float) and Color.RGBA8(byte, byte, byte, byte) is the best solution .. but , it was tremble ..

on the other hand, for some reason, developer even can pass value bigger than 1.0 to GPU to get some "special effect" .... 

I think I will be better if I try to persuade you not to overload it. 🔑
