### ISSUE TITLE
Question about Embed Resources

### ISSUE THREAD

**Issue by TerisbackDev** [endlesstravel/Love2dCS#25]
Is it possible to use Embed Resources without converting Bitmap into Love.Image?
How soon will the 64 bit version be? (I would like to help, but I don’t know how...)

**Comment by TerisbackDev** [comment]
Here is the complete solution for loading embedded resources
```csharp
public static FileData ExtractResource(string filePath)
        {
            Assembly a = Assembly.GetExecutingAssembly();
            filePath = a.GetName().Name + "." + filePath;
            using (System.IO.Stream resourceFileStream = a.GetManifestResourceStream(filePath))
            {
                if (resourceFileStream == null) return null;
                byte[] byByteResource = new byte[resourceFileStream.Length];
                resourceFileStream.Read(byByteResource, 0, byByteResource.Length);
                return FileSystem.NewFileData(byByteResource, filePath);
            }
        }
```
How it looks in **Load()**
```csharp
public override void Load()
        {
            ImageData imageData = Image.NewImageData(ExtractResource("Resources.ManualEvolution.png"));
            Image image = Graphics.NewImage(imageData);
        }
```
"image.png" marked "Build action: Embedded Resource"
![image](https://user-images.githubusercontent.com/26527529/48088642-50607980-e224-11e8-9b6f-f1237c7292fe.png)
Thank you very much @endlesstravel

**Comment by TerisbackDev** [comment]
when I run the 64 bit version it throws 

> System.BadImageFormatException

**Comment by endlesstravel** [comment]
This is a reasonable result, because Love2DCS relies on platform-related DLL files, so calling x86 DLL in. net x64 will cause the call to fail.

Either you build the DLL file of x64 according to the [document](https://github.com/endlesstravel/Love2dCS/blob/master/develop.md#1-windows-), or you wait for the next version. The next version of the nuget package will solve the win-x64 problem.

**Comment by endlesstravel** [comment]
The package Love2dCS 11.0.13 has solve this problem : https://www.nuget.org/packages/Love2dCS/11.0.13 

remember to select target platform : https://github.com/endlesstravel/Love2dCS/blob/master/README-Install.md#1-using-gui

**Comment by TerisbackDev** [comment]
That's right, 64-bit version works.
How the version of your repository is formed?
Where can I see the changelog?

**Comment by endlesstravel** [comment]
Starting with version 11.0.13, I added the native DLL file of x64 to the nuget package, so he was twice as big as the previous package. But don't worry, because the.Target file will automatically select the platform to release the different .Dll  file.

``` XML
<?xml version="1.0" encoding="utf-8"?>
<!-- https://stackoverflow.com/questions/40104838/automatic-native-and-managed-dlls-extracting-from-nuget-package -->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <ItemGroup Condition=" '$(Platform)' == 'x64' ">
        <Content Include="$(MSBuildThisFileDirectory)..\runtimes\win-x64-native\*.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>%(FileName)%(Extension)</Link>
        </Content>
    </ItemGroup>

    <ItemGroup Condition=" '$(Platform)' == 'x86' ">
        <Content Include="$(MSBuildThisFileDirectory)..\runtimes\win-x86-native\*.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>%(FileName)%(Extension)</Link>
        </Content>
    </ItemGroup>

    <Target Name="BeforeBuild" Condition=" '$(Platform)' == 'AnyCPU' " >
       <Error Text="Invalid platform target '$(Platform)' . Please specify the platform target as 'x86' or 'x64'. " />
    </Target>

</Project>
```

I found that x86 DLL suddenly increased by about 2MB from 11.0.9 to 11.0.8. This may be because I changed the compiler environment. I don't remember very well.

Other times, I add annotations and new code every time, so I will get a little bit bigger.
