### ISSUE TITLE
Custom Vertex Format

### ISSUE THREAD

**Issue by jpayne36** [endlesstravel/Love2dCS#59]
Is it in your plans to add custom vertex formats for meshes? They are necessary for making 3d graphics with shaders.

**Comment by endlesstravel** [comment]
that's cool. I mean yes. i check the class of Mesh, it indeed does not have all the features that are done. so, i will finished. 

and because C# is not the same as lua, so i plan to  
* add a class `VertexAttributeFormat` which means the vertex format
* add `Graphics.NewMesh(VertexAttributeFormat, int, MeshDrawMode, SpriteBatchUsage)`
* add `Graphics.NewMesh(VertexAttributeFormat, byte[], MeshDrawMode, SpriteBatchUsage)`
* add `SetVertexAttribute` and `GetVertexAttribute` method.
* change the `Vertex Mesh:GetVertex(int index)` to `byte[] Mesh:GetVertex(int index)`
* change the `void Mesh:SetVertex(int index, Vertex vertex)` to `void Mesh:SetVertex(int index, byte[] data)`

how about that ? If you don't have any other ideas, I'll implement them in the next version.

**Comment by jpayne36** [comment]
Yes that is exactly what I'm looking for, thank you very much. I love the work you are doing by the way, this project is amazing.

**Comment by jpayne36** [comment]
Also there is this way to make a depthbuffer with the canvas in the lua version using this syntax:
canvas = {
		love.graphics.newCanvas(width, height, {format = "rgba8"}),
		depthstencil = love.graphics.newCanvas(width, height, {format = "depth24"})
	}

I'm not sure if this is in your version, if it is could you show me how to do that?

**Comment by endlesstravel** [comment]
thanks for you like it. i don't make a depthbuffer in love, but i known how to set a canvas format , so this may can help you: 
```C#
                int width = 800, height = 600;
                var normalCanvas = Graphics.NewCanvas(width, height, new Graphics.Settings()
                {
                    format = PixelFormat.RGBA8
                });
                var depthStencil = Graphics.NewCanvas(width, height, new Graphics.Settings() {
                    format = PixelFormat.DEPTH24
                });
```

**Comment by jpayne36** [comment]
I think that will work, thank you

**Comment by endlesstravel** [comment]
i Improved support for Mesh modules in version [11.0.27](https://www.nuget.org/packages/Love2dCS/11.0.27)

so it now look like:
```C#
public class IS59 : Scene
{
    public class MyVertex
    {
        [Love.Misc.MeshUtils.Name("VertexPosition")]
        public float x, y;

        [Love.Misc.MeshUtils.Name("VertexColor")]
        public byte r, g, b, a;

        public MyVertex(float x = 0, float y = 0, float z = 0, byte r = 255, byte g = 255, byte b = 255, byte a = 255)
        {
            this.x = x;
            this.y = y;
            this.r = r;
            this.g = g;
            this.b = b;
            this.a = a;
        }
    }
    Mesh mesh;

    public override void Load()
    {
        var info = Love.Misc.MeshUtils.Parse<MyVertex>();
        var rawData = new MyVertex[]
        {
            new MyVertex(20, 10),
            new MyVertex(10, 100),
            new MyVertex(100, 100),
            new MyVertex(100, 10),
        };

        List<MeshAttribFormat> format = info.formatList;
        byte[] data = info.GetData(rawData);
        mesh = Graphics.NewMesh(format, data);
    }

    public override void Draw()
    {
        mesh.SetVertexAttribute(0, 1, new byte[4] { 255, 0, 0, 100 });
        Graphics.Draw(mesh, 100, 100);
    }
}
```
result :
![image](https://user-images.githubusercontent.com/10757838/57582609-7deeee00-74f9-11e9-9f84-582c7ffce40f.png)

**Comment by jpayne36** [comment]
Thank you very much, this solves my problem
